version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure-docker-service:
    build:
      context: ../allure-docker-service
      dockerfile: docker/archive/Dockerfile
      args:
        RELEASE: "2.13.3"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: "TRUE"
      KEEP_HISTORY_LATEST: 5
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ./.data/allure-docker-service/allure-results:/app/allure-results
      #- ./.data/allure-docker-service/projects:/app/projects
